# Spark 的日志很多，只保留 WARN；Paimon 提交相关保留 INFO
rootLogger.level = WARN
rootLogger.appenderRef.console.ref = console
appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss.SSS} %-5p [%c{1}] %m%n

logger.paimon.name = org.apache.paimon
logger.paimon.level = WARN
logger.commit.name = org.apache.paimon.operation.FileStoreCommitImpl
logger.commit.level = INFO
logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = ERROR
logger.sparkutil.name = org.apache.spark.util.Utils
logger.sparkutil.level = ERROR
